### PR TITLE
Build KernelCI API production image

### PR DESCRIPTION
**Pull request by pawiecz**
This PR depends on kernelci/kernelci-core#2332

### CODE REVIEW

**Comment by pawiecz** [comment]
Please do not merge: `--version` argument is broken (taken from `core`, not `api`) and there's also `pip install` issue when building the image (which might be unrelated to this patch but still requires resolving).

**Comment by nuclearcat** [comment]
I converted to draft so it wont be merged by mistake. You can "undraft" it when it is ready

**Comment by pawiecz** [comment]
Version issue resolved in the latest PR revision, install issue resolved in kernelci/kernelci-core#2332 - once the latter is merged, I'll undraft this change (even though it's ready now)

**Comment by nuclearcat** [comment]
Lets try! :)

**Pull request merged**
