### PR TITLE
patches/kernelci-pipeline: use dotted key syntax in TOML settings

### PR DESCRIPTION
**Pull request by JenySadadia**
Update patch used to add TOML settings file for staging to use dotted key syntax.

### CODE REVIEW

**Comment by gctucker** [comment]
I think there's a file outside of git now with credentials on the server, worth double-checking.  If that's the case then we should just remove this one and look into other ways of managing the settings file on staging.

**Comment by JenySadadia** [comment]
> I think there's a file outside of git now with credentials on the server, worth double-checking. If that's the case then we should just remove this one and look into other ways of managing the settings file on staging.

Can you elaborate on what kind of credentials? I tried to check on staging server but couldn't find anything like that.

**Comment by gctucker** [comment]
The `config/staging.kernelci.org.secrets.toml` file has a LAVA API token used for scheduling jobs in Collabora's LAVA lab.

**Comment by gctucker** [comment]
OK I think we can close this PR and just remove the patch that adds this file instead as we can't keep it the actual one under source control with "secrets" such as LAVA API tokens.  We can't really keep it here with git-crypt either as it would make it impossible for users without a GPG key to update the patch series.  We could just add the TOML file with git-crypt in kernelci-pipeline though rather than a patch here.  I think the best approach is still to manage it separately e.g. with Ansible.  It's more of a sysadmin issue at this point (Cc @nuclearcat @VinceHillier).

**Comment by JenySadadia** [comment]
> FYI I've updated the `config/staging.kernelci.org.secrets.toml` file on the staging VM accordingly with `[storage.staging]` and `[runtime.lava-collabora]`

OK. Thanks.

**Comment by JenySadadia** [comment]
> FYI I've updated the `config/staging.kernelci.org.secrets.toml` file on the staging VM accordingly with `[storage.staging]` and `[runtime.lava-collabora]`

I've updated `tarball.storage_config`.

**Comment by JenySadadia** [comment]
> Also this reminds me we should probably be getting the API token from the TOML file rather than the environment with `KCI_API_TOKEN`, I don't think there's any good reason to keep that variable now.

Yes, eventually we can move all the env variables to TOML.

**Comment by gctucker** [comment]
> I've updated `tarball.storage_config`.

Oh, actually I think we should remove the `storage_config` setting from the `[tarball]` section to use the default one instead.

**Comment by JenySadadia** [comment]
As per the discussion above, we should remove `staging.kernelci.org.toml` file instead of maintaining patch file for it.
Also created a GH issue https://github.com/kernelci/kernelci-deploy/issues/134.
Closing the PR.

**Pull request closed without merging**
